//! FFI bindings for libregexp.
//!
//! This module contains the raw bindings generated by bindgen.
//! Most users should use the safe wrappers in the `safe` module instead.

// The actual bindings are included from the build output
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
